### ISSUE TITLE
Download Link Broken

### ISSUE THREAD

**Issue by mrdarcysdream** [bvontob/lpf#1]
Hi There. 
The LPF download link is dead, as i have very limited coding knowledge i dont know how to build this from the code (after trying for a few hours), any help would be appreciated, hoping to add a simple LPF to my NTS-1. Many Thanks.

**Comment by bvontob** [comment]
Thx for your interest in the LPF, and your feedback. I didn't create an "official" release yet for this module, as I wanted to change a few things first (maybe add a tiny amount of feedback and/or saturation to give the filter some more character, right now it's really just the most basic digital low-pass filter you could imagine) - that's why the binary download link was pointing into the void. Sorry about that. I just compiled the current version as an alpha pre-release, so you can download it and play around.

**Comment by mrdarcysdream** [comment]
Thanks for your swift reply and explanation, greatly appreciated. I'll give it a go.

Edit: Yes, this is exactly what i was after, so again thank you very much :)
